### ISSUE TITLE
Create MainFormFieldPanelFactory

### ISSUE THREAD

**Issue by reflect-framework** [reflect-framework/reflect-framework#250]

**Comment by ntenhoeve** [comment]
MainFormFieldPanelFactory that implements Contractor 
Move nth.reflect.fw.ui.GraphicalUserinterfaceController.getPropertyPanelFactory() to GraphicalUserInterfaceApplication.getMainFormFieldPanelFactory

**Comment by reflect-framework** [comment]
Double: See #33
