### ISSUE TITLE
Add custom views support, with a view factory (registered to IntrospectApplication class)

### ISSUE THREAD

**Issue by reflect-framework** [reflect-framework/reflect-framework#32]
Allow a developer to add custom DisplayViews and EditViews  

This is done by adding a editActionMethodParameter, confirmActionMethod and showActionMethodResult methods in an implementation of the UserInterface controller
(e.g. for additional custom views using google maps, charts, blogs, etc)

**Comment by ntenhoeve** [comment]
A future feature could be that the {@link UserInterfaceLayer} also
	 * manages custom views (e.g. for using google maps, charts, etc)
	 * <ul>
	 * <li>A custom view can represent an {@link ActionMethod} parameter or
	 * return value.</li>
	 * <li>A custom view must indicate if it can display an {@link ActionMethod}
	 * parameter or return value with a canHandleAsActionMethodParameter(method)
	 * canHandleAsActionMethodReturnValie(method) methods in the {@link View}
	 * interface</li>
	 * <li>A custom view is registered in the {@link IntrospectApplication}
	 * List<T> getViewClasses() method. (a UI component) should be given by the
	 * ApplicationInterfaceFor..., depending on the userinterface type used</li>
	 * <li>Default views (formview, tableview, etc) should be handled by the
	 * same mechanism. E.G. the IntrospectApplicationFor... could have a default
	 * implementation of the getViews method, that returns formview, tableview,
	 * etc, which could be extended or modified by the user.</li>
	 * </ul>

**Comment by ntenhoeve** [comment]
TODO add in documentation

**Comment by reflect-framework** [comment]
This item is replaced with #319 and #320
